# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
development:
  adapter: mysql2
  encoding: utf8
  database: logistics_dev
  username: root
  password: logistics_12#
  host: 127.0.0.1
  port: 3306
